# Edda Luxembourg S.A.
#
#
name: '${ORG_NAME}'
volumes:
  peer0.${ORG_DOMAIN_NAME}:

networks:
  network.${ORG_DOMAIN_NAME}:
    name: network.${ORG_DOMAIN_NAME}

services:
  
  peer0.${ORG_DOMAIN_NAME}:
    container_name: peer0.${ORG_DOMAIN_NAME}
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.${ORG_DOMAIN_NAME}
      - CORE_PEER_ADDRESS=peer0.${ORG_DOMAIN_NAME}:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.${ORG_DOMAIN_NAME}:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${ORG_DOMAIN_NAME}:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${ORG_DOMAIN_NAME}:7051
      - CORE_PEER_LOCALMSPID=${ORG_NAME}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.${ORG_DOMAIN_NAME}:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0${ORG_NAME}"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../organizations/peerOrganizations/${ORG_DOMAIN_NAME}/peers/peer0.${ORG_DOMAIN_NAME}:/etc/hyperledger/fabric
      - peer0.${ORG_DOMAIN_NAME}:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - network.${ORG_DOMAIN_NAME}