#!/bin/bash

function createOrgIdentities() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/${ORG_DOMAIN}/
  mkdir -p organizations/ordererOrganizations/${ORG_DOMAIN}/
  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-${ORG} --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-${ORG}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-${ORG}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-${ORG}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-${ORG}.pem
    OrganizationalUnitIdentifier: orderer" > "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy ${ORG}'s CA cert to ${ORG}'s /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/tlscacerts/ca.crt"

  # Copy ${ORG}'s CA cert to ${ORG}'s /tlsca directory (for use by Peer clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/tlsca"
  cp "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/tlsca/tlsca.${ORG_DOMAIN}-cert.pem"

  # Copy ${ORG}'s CA cert to ${ORG}'s /ca directory (for use by Peer clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/ca"
  cp "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/ca/ca.${ORG_DOMAIN}-cert.pem"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/msp/tlscacerts/tlsca.${ORG_DOMAIN}-cert.pem"

  # Copy ${ORG}'s CA cert to ${ORG}'s /tlsca directory (for use by Orderer clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/tlsca"
  cp "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/tlsca/tlsca.${ORG_DOMAIN}-cert.pem"

  # Copy ${ORG}'s CA cert to ${ORG}'s /ca directory (for use by Orderer clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/ca"
  cp "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/ca/ca.${ORG_DOMAIN}-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-${ORG} --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-${ORG} --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-${ORG} --id.name ${ORG}admin --id.secret ${ORG}adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-${ORG} --id.name orderer --id.secret ordererpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-${ORG} -M "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-${ORG} -M "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls" --enrollment.profile tls --csr.hosts peer0.${ORG_DOMAIN} --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null
  
  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:7054 --caname ca-${ORG} -M "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:7054 --caname ca-${ORG} -M "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls" --enrollment.profile tls --csr.hosts orderer.${ORG_DOMAIN} --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls/keystore/"* "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/peers/peer0.${ORG_DOMAIN}/tls/server.key"
  
  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/${ORG_DOMAIN}/orderers/orderer.${ORG_DOMAIN}/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-${ORG} -M "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/users/User1@${ORG_DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/users/User1@${ORG_DOMAIN}/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://${ORG}admin:${ORG}adminpw@localhost:7054 --caname ca-${ORG} -M "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/users/Admin@${ORG_DOMAIN}/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORG_DOMAIN}/users/Admin@${ORG_DOMAIN}/msp/config.yaml"
}